# Generated by Django 3.1.2 on 2020-12-04 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacioncodigo',
            name='username',
        ),
        migrations.AddField(
            model_name='validacioncodigo',
            name='codigo_ingresado',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='validacioncodigo',
            name='date_init',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validacioncodigo',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validacioncodigo',
            name='codigo',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
